services:
  habittracker.api:
    image: ${DOCKER_REGISTRY-}habittrackerapi
    build:
      context: .
      dockerfile: src/habittracker.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      # Seq
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://habittracker.seq:5341/ingest/otlp
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://habittracker.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    depends_on:
      - habittracker.postgres

  habittracker.postgres:
    image: postgres:17.2 # or latest
    environment:
      POSTGRES_DB: habittracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  habittracker.seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - 8080:80
      - 5341:5341

  habittracker.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
