// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HabitTracker.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_UserId_Reference : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DELETE FROM habit_tracker.Habits;
                DELETE FROM habit_tracker.Tags;
                DELETE FROM habit_tracker.HabitTags;
                """);

            migrationBuilder.DropIndex(
                name: "IX_Tags_Name",
                schema: "habit_tracker",
                table: "Tags");

            migrationBuilder.AddColumn<string>(
                name: "UserId",
                schema: "habit_tracker",
                table: "Tags",
                type: "character varying(500)",
                maxLength: 500,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "UserId",
                schema: "habit_tracker",
                table: "Habits",
                type: "character varying(500)",
                maxLength: 500,
                nullable: false,
                defaultValue: "");

            migrationBuilder.CreateIndex(
                name: "IX_Tags_UserId_Name",
                schema: "habit_tracker",
                table: "Tags",
                columns: new[] { "UserId", "Name" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Habits_UserId",
                schema: "habit_tracker",
                table: "Habits",
                column: "UserId");

            migrationBuilder.AddForeignKey(
                name: "FK_Habits_Users_UserId",
                schema: "habit_tracker",
                table: "Habits",
                column: "UserId",
                principalSchema: "habit_tracker",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Tags_Users_UserId",
                schema: "habit_tracker",
                table: "Tags",
                column: "UserId",
                principalSchema: "habit_tracker",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Habits_Users_UserId",
                schema: "habit_tracker",
                table: "Habits");

            migrationBuilder.DropForeignKey(
                name: "FK_Tags_Users_UserId",
                schema: "habit_tracker",
                table: "Tags");

            migrationBuilder.DropIndex(
                name: "IX_Tags_UserId_Name",
                schema: "habit_tracker",
                table: "Tags");

            migrationBuilder.DropIndex(
                name: "IX_Habits_UserId",
                schema: "habit_tracker",
                table: "Habits");

            migrationBuilder.DropColumn(
                name: "UserId",
                schema: "habit_tracker",
                table: "Tags");

            migrationBuilder.DropColumn(
                name: "UserId",
                schema: "habit_tracker",
                table: "Habits");

            migrationBuilder.CreateIndex(
                name: "IX_Tags_Name",
                schema: "habit_tracker",
                table: "Tags",
                column: "Name",
                unique: true);
        }
    }
}
