// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HabitTracker.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_HabitTags : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "HabitTags",
                schema: "habit_tracker",
                columns: table => new
                {
                    HabitId = table.Column<string>(type: "character varying(500)", nullable: false),
                    TagId = table.Column<string>(type: "character varying(500)", nullable: false),
                    CreatedAtUtc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HabitTags", x => new { x.HabitId, x.TagId });
                    table.ForeignKey(
                        name: "FK_HabitTags_Habits_HabitId",
                        column: x => x.HabitId,
                        principalSchema: "habit_tracker",
                        principalTable: "Habits",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_HabitTags_Tags_TagId",
                        column: x => x.TagId,
                        principalSchema: "habit_tracker",
                        principalTable: "Tags",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_HabitTags_TagId",
                schema: "habit_tracker",
                table: "HabitTags",
                column: "TagId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "HabitTags",
                schema: "habit_tracker");
        }
    }
}
